baseURL = "https://genivi.github.io/vehicle_signal_specification/"
languageCode = "en-us"
title = "Vehicle Signal Specification"
theme = "learn"
publishDir = "../docs"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"
  disableInlineCopyToClipBoard = true
  editURL = "https://github.com/genivi/vehicle_signal_specification/edit/master/docs-gen/content/"
  disableLandingPageButton = true


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/genivi/vehicle_signal_specification"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-download'></i> Releases"
url = "https://github.com/GENIVI/vehicle_signal_specification/releases"
weight = 12
