name: Standard Build Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  buildtest:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install vss-tools dependencies
        run: |
          python -V
          python -m pip --quiet --no-input install --upgrade pip
          python -m pip --quiet --no-input install --upgrade  wheel
          cd vss-tools
          pip install -e .
          pip install pytest
          # idlc currently used both during python test and later in this script
          pip install cyclonedds
          sudo apt install -y protobuf-compiler
          echo done!

      - name: Test mandatory targets
        run: |
          make mandatory_targets

      - name: Test that ddsidl is correct
        run: |
          idlc vss_rel_*.idl

      - name: Test optional targets. NOTE - always succeeds
        run: |
          make -k optional_targets || true

      - name: Install hugo
        env:
          HUGO_VER : 0.103.1
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_${HUGO_VER}_linux-amd64.deb
          sudo dpkg -i hugo_${HUGO_VER}_linux-amd64.deb

      - name: Make docs
        run: |
          hugo -s ./docs-gen

      - name: Deploy docs
        # Only deploy docs if this was a push to master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          commit-message: Auto-deploy docs built from commit ${{ github.sha }}
