name: Create Draft Release

on:
  workflow_dispatch: # input version manually. Overrides push tag
    inputs:
      vss-version:
        description: "Release version (numerical version), e.g. 4.2, 4.2rc0"
        required: true
        default: "0.0.0"

# Needed if GITHUB_TOKEN by default do not have right to create release
permissions:
  contents: write
  packages: write

jobs:
  call_kuksa_databroker_build:
    uses: ./.github/workflows/buildcheck.yml
    with:
      vss-version: ${{ inputs.vss-version }}

  create_release:
    runs-on: ubuntu-latest
    needs:
      [
        call_kuksa_databroker_build
      ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts
          merge-multiple: true
      - name: Display structure of downloaded files
        run: |
             ls -R build-artifacts

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: "v${{ inputs.vss-version }}"
          fail_on_unmatched_files: true
          files: |
            build-artifacts/*
            spec/units.yaml
            spec/quantities.yaml
